In [177]:
import numpy as np

In [178]:
np.__version__

'1.22.3'

In [179]:
a =np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [180]:
a[4]=(1)
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [181]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [182]:
x =  np.arange(0, 9).reshape(3,3)
x


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [183]:
a = np.array ([1,2,0,0,4,0])
b =np.nonzero(a)
b

(array([0, 1, 4]),)

In [184]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [185]:
np.random.random(3)

array([0.73832064, 0.06253706, 0.55707001])

In [186]:
z=np.random.random(10)

In [187]:
np.min(z)

0.0903513067325945

In [188]:
np.max(z)

0.8870812012959122

In [189]:
u= np.random.random(30)
np.mean(u)

0.5291524331565898

In [190]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [191]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.35505961 0.41655823 1.         0.31894589 0.40652154]
 [0.86212183 0.0853108  0.91587513 0.95189731 0.10782398]
 [0.         0.74322443 0.64366374 0.40979693 0.33598704]
 [0.30539298 0.64324604 0.2971521  0.85040582 0.8306413 ]
 [0.11743289 0.05593644 0.30417886 0.40532911 0.7716474 ]]


In [192]:
d=np.random.randint(0,6,(3,3))
e=np.random.randint(2,6,(3,3))
print(d)
print(e)
np.intersect1d(d,e)

[[1 2 0]
 [2 5 5]
 [1 2 4]]
[[2 4 3]
 [2 3 5]
 [5 5 3]]


array([2, 4, 5])

In [193]:
f=np.random.rand(10)
np.sort(f)

array([0.02793183, 0.08774092, 0.11883991, 0.15131276, 0.17518534,
       0.20089624, 0.6694007 , 0.73377766, 0.84693822, 0.96709866])

In [194]:
Z = np.random.random(10)
print(z)
Z[Z.argmax()] = 0
print(Z)

[0.57491338 0.8870812  0.09035131 0.74639375 0.19657879 0.69317529
 0.62411574 0.17848444 0.49798085 0.41521611]
[0.41342939 0.         0.07336519 0.16664137 0.026013   0.81598945
 0.75360997 0.78639403 0.87238372 0.26628892]


In [195]:
X = np.random.rand(5, 10)
x.mean(axis=1,keepdims=True)

array([[1.],
       [4.],
       [7.]])

In [196]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9997 9998 9999 9996 9995]


In [197]:
x = 3*np.random.randn(3, 5)
x

array([[-0.12807462,  3.31695297, -0.8759313 , -2.70308917,  1.1088108 ],
       [-5.64116773, -3.41871048,  2.2436485 , -1.69950302, -1.54259358],
       [ 0.03577589, -0.14538965,  0.7466148 , -2.47908765,  5.90307662]])

In [198]:
z=np.where(x<4,x,x**2)
z

array([[-0.12807462,  3.31695297, -0.8759313 , -2.70308917,  1.1088108 ],
       [-5.64116773, -3.41871048,  2.2436485 , -1.69950302, -1.54259358],
       [ 0.03577589, -0.14538965,  0.7466148 , -2.47908765, 34.84631362]])